version: '3.8'
services:
  redis:
    image: redis:7.0.4-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  api:
    image: $IMAGE
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
  qr:
    image: $QR_IMAGE
    ports:
      - 8050:8050
    environment:
      - TOKEN_ENDPOINT=http://api:8000/token
      - SECRETS_ENDPOINT=http://api:8000/secrets
  messages:
    image: $MESSAGES_IMAGE
    ports:
      - 8051:8051
    environment:
      - MESSAGES_ENDPOINT=http://api:8000/messages
volumes:
  redis:
    driver: local
