version: '3.8'
services:
  redis:
    image: redis:7.0.4-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  message-api:
    image: $IMAGE
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
volumes:
  redis:
    driver: local
