name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - uses: actions/checkout@v3
    - name: Build the Docker base image
      run: |
        docker build . --file docker/Dockerfile.base --tag registry.digitalocean.com/dwe/message-api-base:$(echo $GITHUB_SHA | head -c7)
        docker push registry.digitalocean.com/dwe/message-api-base:$(echo $GITHUB_SHA | head -c7)
        docker build . --file docker/Dockerfile --tag registry.digitalocean.com/dwe/message-api:$(echo $GITHUB_SHA | head -c7) --build-arg message-api-base:$(echo $GITHUB_SHA | head -c7)
        docker push registry.digitalocean.com/dwe/message-api:$(echo $GITHUB_SHA | head -c7)
